// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class AiGeneration
{
    public int Id { get; set; }

    public int PostId { get; set; }

    public string Prompt { get; set; }

    public string GeneratedCaption { get; set; }

    public string VisionAnalysis { get; set; }

    public int? TokensUsed { get; set; }

    public string Model { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Post Post { get; set; }
}