// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class BrandSetting
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string BrandName { get; set; }

    public string ToneStyle { get; set; }

    public string CaptionLength { get; set; }

    public int? EmojiLevel { get; set; }

    public string CtaStyle { get; set; }

    public string WritingLanguage { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}