// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class GoogleDriveConnection
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string GoogleEmail { get; set; }

    public string AccessToken { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? TokenExpiredAt { get; set; }

    public string FolderId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}