// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class PostPlatform
{
    public int Id { get; set; }

    public int PostId { get; set; }

    public string Platform { get; set; }

    public int? SocialAccountId { get; set; }

    public string PlatformPostId { get; set; }

    public string Status { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime? PublishedAt { get; set; }

    public virtual Post Post { get; set; }

    public virtual SocialAccount SocialAccount { get; set; }
}