// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class ScheduledJob
{
    public int Id { get; set; }

    public int PostId { get; set; }

    public string JobType { get; set; }

    public DateTime ExecuteAt { get; set; }

    public string Status { get; set; }

    public int? RetryCount { get; set; }

    public string LastError { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Post Post { get; set; }
}