// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class SocialAccount
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Platform { get; set; }

    public string PlatformUserId { get; set; }

    public string PageId { get; set; }

    public string AccessToken { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? TokenExpiredAt { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<PostPlatform> PostPlatforms { get; set; } = new List<PostPlatform>();

    public virtual User User { get; set; }
}