// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Repositories.Entities;

namespace Repositories.DBContext;

public partial class toolContext : DbContext
{
    public toolContext(DbContextOptions<toolContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AiGeneration> AiGenerations { get; set; }

    public virtual DbSet<BrandSetting> BrandSettings { get; set; }

    public virtual DbSet<GoogleDriveConnection> GoogleDriveConnections { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<PostImage> PostImages { get; set; }

    public virtual DbSet<PostPlatform> PostPlatforms { get; set; }

    public virtual DbSet<ScheduledJob> ScheduledJobs { get; set; }

    public virtual DbSet<SocialAccount> SocialAccounts { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AiGeneration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("ai_generations_pkey");

            entity.ToTable("ai_generations");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.GeneratedCaption).HasColumnName("generated_caption");
            entity.Property(e => e.Model)
                .HasMaxLength(100)
                .HasColumnName("model");
            entity.Property(e => e.PostId).HasColumnName("post_id");
            entity.Property(e => e.Prompt).HasColumnName("prompt");
            entity.Property(e => e.TokensUsed)
                .HasDefaultValue(0)
                .HasColumnName("tokens_used");
            entity.Property(e => e.VisionAnalysis).HasColumnName("vision_analysis");

            entity.HasOne(d => d.Post).WithMany(p => p.AiGenerations)
                .HasForeignKey(d => d.PostId)
                .HasConstraintName("ai_generations_post_id_fkey");
        });

        modelBuilder.Entity<BrandSetting>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("brand_settings_pkey");

            entity.ToTable("brand_settings");

            entity.HasIndex(e => e.UserId, "brand_settings_user_id_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.BrandName)
                .HasMaxLength(255)
                .HasColumnName("brand_name");
            entity.Property(e => e.CaptionLength)
                .HasMaxLength(50)
                .HasColumnName("caption_length");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CtaStyle)
                .HasMaxLength(100)
                .HasColumnName("cta_style");
            entity.Property(e => e.EmojiLevel)
                .HasDefaultValue(1)
                .HasColumnName("emoji_level");
            entity.Property(e => e.ToneStyle)
                .HasMaxLength(100)
                .HasColumnName("tone_style");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.WritingLanguage)
                .HasMaxLength(50)
                .HasColumnName("writing_language");

            entity.HasOne(d => d.User).WithOne(p => p.BrandSetting)
                .HasForeignKey<BrandSetting>(d => d.UserId)
                .HasConstraintName("brand_settings_user_id_fkey");
        });

        modelBuilder.Entity<GoogleDriveConnection>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("google_drive_connections_pkey");

            entity.ToTable("google_drive_connections");

            entity.HasIndex(e => e.UserId, "idx_google_drive_connections_user");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccessToken).HasColumnName("access_token");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.FolderId).HasColumnName("folder_id");
            entity.Property(e => e.GoogleEmail)
                .HasMaxLength(255)
                .HasColumnName("google_email");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.RefreshToken).HasColumnName("refresh_token");
            entity.Property(e => e.TokenExpiredAt)
                .HasColumnType("timestamp with time zone")
                .HasColumnName("token_expired_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.GoogleDriveConnections)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("google_drive_connections_user_id_fkey");
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("posts_pkey");

            entity.ToTable("posts");

            entity.HasIndex(e => e.ScheduledAt, "idx_posts_scheduled_at");

            entity.HasIndex(e => new { e.UserId, e.Status }, "idx_posts_user_status");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AiTitle)
                .HasMaxLength(255)
                .HasColumnName("ai_title");
            entity.Property(e => e.Caption).HasColumnName("caption");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.ContentType)
                .HasMaxLength(100)
                .HasColumnName("content_type");
            entity.Property(e => e.EditedByUser)
                .HasDefaultValue(false)
                .HasColumnName("edited_by_user");
            entity.Property(e => e.FacebookPostId)
                .HasMaxLength(255)
                .HasColumnName("facebook_post_id");
            entity.Property(e => e.GenerationVersion)
                .HasDefaultValue(1)
                .HasColumnName("generation_version");
            entity.Property(e => e.Hashtags)
                .HasColumnName("hashtags");
            entity.Property(e => e.MoodType)
                .HasMaxLength(100)
                .HasColumnName("mood_type");
            entity.Property(e => e.PublishedAt)
                .HasColumnType("timestamp with time zone")
                .HasColumnName("published_at");
            entity.Property(e => e.ScheduledAt)
                .HasColumnType("timestamp with time zone")
                .HasColumnName("scheduled_at");
            entity.Property(e => e.SceneType)
                .HasMaxLength(100)
                .HasColumnName("scene_type");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'Draft'::character varying")
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Posts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("posts_user_id_fkey");
        });

        modelBuilder.Entity<PostImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("post_images_pkey");

            entity.ToTable("post_images");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.DisplayOrder)
                .HasDefaultValue(1)
                .HasColumnName("display_order");
            entity.Property(e => e.GoogleDriveFileId).HasColumnName("google_drive_file_id");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasColumnName("image_url");
            entity.Property(e => e.PostId).HasColumnName("post_id");

            entity.HasOne(d => d.Post).WithMany(p => p.PostImages)
                .HasForeignKey(d => d.PostId)
                .HasConstraintName("post_images_post_id_fkey");
        });

        modelBuilder.Entity<PostPlatform>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("post_platforms_pkey");

            entity.ToTable("post_platforms");

            entity.HasIndex(e => new { e.PostId, e.Platform }, "idx_post_platforms_post_platform");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ErrorMessage).HasColumnName("error_message");
            entity.Property(e => e.Platform)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("platform");
            entity.Property(e => e.PlatformPostId)
                .HasMaxLength(255)
                .HasColumnName("platform_post_id");
            entity.Property(e => e.PostId).HasColumnName("post_id");
            entity.Property(e => e.PublishedAt)
                .HasColumnType("timestamp with time zone")
                .HasColumnName("published_at");
            entity.Property(e => e.SocialAccountId).HasColumnName("social_account_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValueSql("'Pending'::character varying")
                .HasColumnName("status");

            entity.HasOne(d => d.Post).WithMany(p => p.PostPlatforms)
                .HasForeignKey(d => d.PostId)
                .HasConstraintName("post_platforms_post_id_fkey");

            entity.HasOne(d => d.SocialAccount).WithMany(p => p.PostPlatforms)
                .HasForeignKey(d => d.SocialAccountId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("post_platforms_social_account_id_fkey");
        });

        modelBuilder.Entity<ScheduledJob>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("scheduled_jobs_pkey");

            entity.ToTable("scheduled_jobs");

            entity.HasIndex(e => new { e.Status, e.ExecuteAt }, "idx_scheduled_jobs_status_execute");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.ExecuteAt)
                .HasColumnType("timestamp with time zone")
                .HasColumnName("execute_at");
            entity.Property(e => e.JobType)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("job_type");
            entity.Property(e => e.LastError).HasColumnName("last_error");
            entity.Property(e => e.PostId).HasColumnName("post_id");
            entity.Property(e => e.RetryCount)
                .HasDefaultValue(0)
                .HasColumnName("retry_count");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValueSql("'Pending'::character varying")
                .HasColumnName("status");

            entity.HasOne(d => d.Post).WithMany(p => p.ScheduledJobs)
                .HasForeignKey(d => d.PostId)
                .HasConstraintName("scheduled_jobs_post_id_fkey");
        });

        modelBuilder.Entity<SocialAccount>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("social_accounts_pkey");

            entity.ToTable("social_accounts");

            entity.HasIndex(e => new { e.UserId, e.Platform }, "idx_social_accounts_user_platform");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccessToken).HasColumnName("access_token");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.PageId)
                .HasMaxLength(255)
                .HasColumnName("page_id");
            entity.Property(e => e.Platform)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("platform");
            entity.Property(e => e.PlatformUserId)
                .HasMaxLength(255)
                .HasColumnName("platform_user_id");
            entity.Property(e => e.RefreshToken).HasColumnName("refresh_token");
            entity.Property(e => e.TokenExpiredAt)
                .HasColumnType("timestamp with time zone")
                .HasColumnName("token_expired_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.SocialAccounts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("social_accounts_user_id_fkey");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("users_pkey");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "users_email_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .HasMaxLength(255)
                .HasColumnName("full_name");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasColumnName("password_hash");
            entity.Property(e => e.Plan)
                .HasMaxLength(50)
                .HasDefaultValueSql("'free'::character varying")
                .HasColumnName("plan");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.FcmToken)
    .HasColumnName("fcm_token");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
